export const employeesData = [
    {
        id: "1",
        name: "Juan Perez",
        position: "Desarrollador",
        department: "IT",
        salary: 50000,
        hiringDate: "2023-01-15",
        isActive: true,
    },
    {
        id: "2",
        name: "Ana Gomez",
        position: "Diseñadora",
        department: "Marketing",
        salary: 45000,
        hiringDate: "2022-07-10",
        isActive: true,
    },
    {
        id: "3",
        name: "Carlos Lopez",
        position: "Gerente",
        department: "Contabilidad",
        salary: 70000,
        hiringDate: "2020-03-20",
        isActive: false,
    },
    {
        id: "4",
        name: "Maria Fernandez",
        position: "Analista",
        department: "IT",
        salary: 40000,
        hiringDate: "2021-11-05",
        isActive: true,
    },
    {
        id: "5",
        name: "Luis Martinez",
        position: "Soporte Técnico",
        department: "IT",
        salary: 35000,
        hiringDate: "2023-03-01",
        isActive: true,
    },
    {
        id: "6",
        name: "Sofia Ramirez",
        position: "Especialista en SEO",
        department: "Marketing",
        salary: 48000,
        hiringDate: "2022-09-15",
        isActive: true,
    },
    {
        id: "7",
        name: "Pedro Gonzalez",
        position: "Contador",
        department: "Financias",
        salary: 60000,
        hiringDate: "2021-06-20",
        isActive: false,
    },
    {
        id: "8",
        name: "Laura Torres",
        position: "Desarrolladora",
        department: "IT",
        salary: 52000,
        hiringDate: "2020-12-10",
        isActive: true,
    },
];
